datacarpentry/python-ecology-lesson-es

CODE_OF_CONDUCT.md
CONTRIBUTING.md

translate contributing and coc

---

README.md
fechas-progreso.md

para https://github.com/Carpentries-ES/python-ecology-lesson-es/issues/4 cc @orchid00

crear tabla con fechas

---

_episodes/03-index-slice-subset.md

Traducido hasta la linea 123. Por favor verificar.
---
Agradecemos tu tiempo y esfuerzo para mejorar esta lección. ¡Gracias por contribuir!
Si esta contribución es parte de tu capacitación como **instructor**, envía un correo electrónico a [checkout@carpentries.org](mailto:checkout@carpentries.org) con un enlace a ésta contribución para que podamos registrar su progreso.
Por favor ten en cuenta que los **Maintainers** son voluntarios y pueden tardar más de 72 horas en responder. Si tienes alguna pregunta sobre el proceso de mantenimiento de la lección o te gustaría ofrecer su tiempo como **Maintainer**, comunícate en el [canal de Slack en español] (https://swcarpentry.slack.com/messages/CDZLNHSMQ)
---

Traducido hasta la linea 123.

---

_episodes/00-before-we-start.md

Listo esta parte. En alguno lados se complicaba hacer una traducción textual así que puede que haya modificado algunas de las frases para que sean mas entendibles.
Quedo atento a cualquier corrección.
Leo

Traducción 00-before-we-start.md completa

---

index.md

Modificación de la traducción "Getting started" como "Antes de empezar"

---

_episodes/04-data-types-and-format.md

Traducción de la lección hasta la línea 68 de la versión en inglés.

Traducido hasta la linea 68

---

_episodes/00-before-we-start.md

Algunas correcciones de ortografía, señalar en negrita terminos tecnicos sin traducir segun las convenciones.

1ra revisión de episodio

---

_episodes/03-index-slice-subset.md

Se cambiaron algunas letras para estar acorde con el todo informal del "tu".
Se tradujo hasta la linea 235.
---
Agradecemos tu tiempo y esfuerzo para mejorar esta lección. ¡Gracias por contribuir!
Si esta contribución es parte de tu capacitación como **instructor**, envía un correo electrónico a [checkout@carpentries.org](mailto:checkout@carpentries.org) con un enlace a ésta contribución para que podamos registrar su progreso.
Por favor ten en cuenta que los **Maintainers** son voluntarios y pueden tardar más de 72 horas en responder. Si tienes alguna pregunta sobre el proceso de mantenimiento de la lección o te gustaría ofrecer su tiempo como **Maintainer**, comunícate en el [canal de Slack en español] (https://swcarpentry.slack.com/messages/CDZLNHSMQ)
---

Traducido hasta la linea 235

---

_extras/jupyter_notebooks.md
reference.md

Se necesita (mínimo) revisar:
1. CSV -  Carriage return character ? no se como es en español
2. Float - representacion de un punto flotante ? 
3. SQLite - Motor de base de datos ? es lo que mejor se me ocurrió pero necesita revisarse por otra personas para tomar una decision sobre como traducir _database engine_ si es que se traducirá

traducción de reference.md

---

_episodes/09-working-with-sql.md

how does this look @raynamharris ?

adding a few english words

---

setup.md

Here is my initial translation for #17. I suggested a few grammatical changes in the original english lesson (see https://github.com/datacarpentry/python-ecology-lesson/pull/327), so my translation is based off my suggested wording there in some cases.

traduccion de setup.md

---

_episodes/04-data-types-and-format.md

Traducción completa del episodio 4. Sujeta a revisión.

Traducción completa. Sujeta a revisión. episodio 04

---

_episodes/03-index-slice-subset.md

Traducido hasta la linea 305. Por favor verificar.
Wil

Linea 305 del episodio 03

---

_episodes/03-index-slice-subset.md

Episodio 03 - traducción hasta la línea 502

---

_episodes/09-working-with-sql.md

revision del episodio 09 - listo para segunda revision 
@orchid00

Episode 09 revision 1

---

_episodes/06-loops-and-functions.md

In this pull request I contribute a translation of episode 6 for this lesson.
I have a question regarding a term: How should we translate *statement*?
Cheers!

Translation of episode 6: loops and functions.

---

_episodes/02-starting-with-data.md

Se ha traducido la lección 2. Resolves #7

Episode 02 translation to Spanish

---

_episodes/03-index-slice-subset.md

Tengo unas dudas.
1. En la línea 501 se habla de que la situación descrita se discutirá en la lección 3 pero este es el final de la lección 3. Esto es un Typo?
2. No estoy seguro de la traducción del último desafío, por favor revísalo.
Wil

Traducción completa episodio 03

---

index.md

Aqui agregué la nota
Ref: https://github.com/Carpentries-ES/board/issues/27
FYI @agbeltran @LUS24 @NPalopoli 
@raynamharris los honoer del merge :)

Agregar nota en index

---

_episodes/08-putting-it-all-together.md

episode 08

---

_includes/carpentries.html
_includes/lesson_footer.html

There were some merge comments on some files. I remove those comments and fix any marge issue

Fix merge comments on pages

---

_episodes/02-starting-with-data.md

Hay palabras repetidas erróneamente

Removed wrongly repeated words

---

_episodes/02-starting-with-data.md

el espacio estaba mal para "acerca de"

Error sintáctico menor

---

setup.md

Same as https://github.com/datacarpentry/python-ecology-lesson/pull/431 ;-)

Link to new conda homepage

---

_episodes/01-short-introduction-to-Python.md
_episodes/02-starting-with-data.md
_episodes/03-index-slice-subset.md
_episodes/04-data-types-and-format.md
_episodes/05-merging-data.md
_episodes/06-loops-and-functions.md
_episodes/07-visualization-ggplot-python.md
_episodes/08-putting-it-all-together.md
_episodes/09-working-with-sql.md

Add and modify key points in all lessons.

---

_episodes/00-before-we-start.md
_episodes/01-short-introduction-to-Python.md
_episodes/02-starting-with-data.md
_episodes/04-data-types-and-format.md
_episodes/06-loops-and-functions.md

fixing format in the first page to display correctly title and objectives

fix headings

---

_episodes/07-visualization-ggplot-python.md

Alt text para gráficas 06_alpha_plot, 06_blue_plot y 06_first_plot

Agregar alt text para gráficas

---

_episodes/00-before-we-start.md

I found that the link to spider ide website was broken, so I replaced it.
I also remove necessaries `<br \>` in the file.

Fix link in 00-before-we-start
